# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apps.django_socio_grpc_quickstart.grpc import django_socio_grpc_quickstart_pb2 as apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class QuestionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/Create',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRequest.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
                )
        self.CustomRetrieve = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/CustomRetrieve',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveRequest.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveResponse.FromString,
                )
        self.CustomRetrieveWithBaseProtoSerializer = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/CustomRetrieveWithBaseProtoSerializer',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveWithBaseProtoSerializerRequest.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionBaseProtoExampleResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/Destroy',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/List',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionListRequest.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionListResponse.FromString,
                )
        self.MethodSerializerFieldExample = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/MethodSerializerFieldExample',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.MethodSerializerFieldExampleResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/PartialUpdate',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionPartialUpdateRequest.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/Retrieve',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRetrieveRequest.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/drf_template.django_socio_grpc_quickstart.QuestionController/Update',
                request_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRequest.SerializeToString,
                response_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
                )


class QuestionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomRetrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomRetrieveWithBaseProtoSerializer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MethodSerializerFieldExample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuestionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRequest.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.SerializeToString,
            ),
            'CustomRetrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomRetrieve,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveRequest.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveResponse.SerializeToString,
            ),
            'CustomRetrieveWithBaseProtoSerializer': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomRetrieveWithBaseProtoSerializer,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveWithBaseProtoSerializerRequest.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionBaseProtoExampleResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionListRequest.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionListResponse.SerializeToString,
            ),
            'MethodSerializerFieldExample': grpc.unary_unary_rpc_method_handler(
                    servicer.MethodSerializerFieldExample,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.MethodSerializerFieldExampleResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionPartialUpdateRequest.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRetrieveRequest.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRequest.FromString,
                    response_serializer=apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drf_template.django_socio_grpc_quickstart.QuestionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuestionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/Create',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRequest.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CustomRetrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/CustomRetrieve',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveRequest.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CustomRetrieveWithBaseProtoSerializer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/CustomRetrieveWithBaseProtoSerializer',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionCustomRetrieveWithBaseProtoSerializerRequest.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionBaseProtoExampleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/Destroy',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/List',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionListRequest.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MethodSerializerFieldExample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/MethodSerializerFieldExample',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.MethodSerializerFieldExampleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/PartialUpdate',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionPartialUpdateRequest.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/Retrieve',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRetrieveRequest.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drf_template.django_socio_grpc_quickstart.QuestionController/Update',
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionRequest.SerializeToString,
            apps_dot_django__socio__grpc__quickstart_dot_grpc_dot_django__socio__grpc__quickstart__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
