# Generated by Django 2.2.7 on 2021-11-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='删除时间'),
        ),
    ]
