# Generated by Django 2.2.7 on 2022-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='删除时间'),
        ),
    ]
