# Generated by Django 2.2.7 on 2022-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '商品标签',
                'db_table': 'goods_tag',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('tags', models.ManyToManyField(related_name='goods', to='goods.GoodsTag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'goods',
            },
        ),
    ]
