# Generated by Django 2.2.5 on 2023-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_socio_grpc_quickstart', '0002_auto_20230110_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='like count'),
        ),
    ]
