# Generated by Django 2.2.5 on 2023-08-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(db_index=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='名称')),
                ('desc', models.TextField(blank=True, default='', verbose_name='描述')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, '书籍'), (2, '杂志')], default=1, help_text="{1: '书籍', 2: '杂志'}", verbose_name='类型')),
                ('creator', models.ForeignKey(db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
    ]
